SELECT 
	E1_FILIAL AS filial,
	E1_XCONPAR AS contrato,
	TRIM(CONCAT(E1_FILIAL,E1_XCONPAR)) AS filialcontrato,
	E1_NUM AS num_titulo,
	E1_XFLUIG AS proposta_fluig,
	E1_PREFIXO AS prefixo,
	E1_NUMNOTA AS num_nf,
	E1_PARCELA AS parcela,
	E1_TIPO AS tipo,
	E1_SALDO AS saldo,
	E1_NATUREZ AS cod_natureza,
	E1_CLIENTE AS cod_cliente,
	E1_LOJA AS cod_loja,
	E1_NOMCLI AS nome_cliente,
	CONVERT(DATE,E1_EMISSAO) AS data_emissao,
	CONVERT(DATE,E1_VENCTO) AS data_vencimento,
	CONVERT(DATE,E1_VENCREA) AS vencimento_real,
	CONVERT(FLOAT,E1_VALOR) AS valor_titulo,
	E1_HIST AS historico,
	CONVERT(FLOAT,E1_VLCRUZ) AS valor_titulo_moeda,
	E1_FLUXO AS fluxo_caixa,
	E1_FORMREC AS cod_forma_pagamento,
	E1_XEVEN AS evento_parcela,
	E1_XFOR AS forma_pagamento_parcela,
	E1_VEND2 AS cod_vendedor2,
	E1_VEND3 AS cod_vendedor3,
	NULLIF(CONVERT(DATE,E1_DTACRED), '1900-01-01') AS data_compensacao,
	E1_CCUSTO AS centro_custo,
	E1_ITEMCTA AS item_contabil,
	E1_MODSPB AS modalidade_rec_previsto,
	NULLIF(CONVERT(DATE,E1_BAIXA), '1900-01-01') AS data_baixa,
	E1_PEDIDO AS cod_pedido,
	TIMESTAMP AS data_stamp
FROM SE1010 
WHERE 1 = 1