SELECT DISTINCT
  C7_FILIAL AS filial,
  C7_ITEM AS cod_item,
  C7_PRODUTO AS cod_produto,
  C7_DESCRI AS descricao,
  C7_UM AS un_medida,
  B1_TIPO AS tipo_pedido,
  C7_QUANT AS qt_comprada,
  C7_QUJE AS qt_entregue,
  STATUS_CONDICAO AS condicao,
  C7_PRECO AS vl_unitario,
  C7_VLDESC AS vl_desconto,
  C7_TOTAL AS vl_total,
  C7_NUMSC AS num_sc,
  C7_NUM AS num_pedido,
  CONVERT(date, DT_EMISSAO_PEDIDO) AS dt_emissao_pedido,
  CONVERT(date, DT_ENTREGA) AS dt_entrega,
  FORNECEDOR AS fornecedor,
  CNPJ_FORNEC AS cnpj_fornecedor,
  CTT_DESC01 AS desc_cc,
  COMPRADOR AS comprador,
  C1_SOLICIT AS solicitante,
  PRIORIDADE AS prioridade,
  CONVERT(date, DT_APROV_SC) AS dt_aprov_sc,
  CONCAT(C7_FILIAL, CODIGO_COND_PAGAMENTO) AS filial_codpag,
  CODIGO_COND_PAGAMENTO AS cod_cond_pagamento,
  DESCRICAO_COND_PAGAMENTO AS desc_cond_pagamento,
  DESC_FORMA_PAGAMENTO AS desc_forma_pagamento,
  GRUPO AS grupo,
  CONVERT(date, DATA_PREVISTA_ENTREGA) AS dt_prevista_entrega,
  TIPO AS tipo,
  EMAIL_FORNECE AS email_fornecedor,
  COD_FORNECE AS cod_fornecedor,
  COD_COMPRADOR AS cod_comprador
FROM VW_PEDIDOS_COMPRAS NOLOCK
WHERE 1 = 1