SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM information_schema.COLUMNS
WHERE COLUMN_NAME LIKE '%tipoPromocaoDesc%'
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;